# yaml-language-server: $schema=none
client_listen_address: ":8080"
replica_listen_address: ":9090"

nodes:
  - id: node-a
    replica_address: node-a:9090

  - id: node-b
    replica_address: node-b:9090

  - id: node-c
    replica_address: node-c:9090
